---
title: "Vertically stacked barcharts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(readxl)
library(janitor)
```

### Get data
```{r eval = TRUE}
extract_xls <- "data/DATA EXTRACTION FINAL.xlsx"
de <- read_excel(extract_xls, sheet = "Summary DE")
bar_data <- de %>% 
  select(Country, `Biosphere reserve`, `Type of data`, `Data source`, `Study design`)
names(bar_data) <- c('Country', 'Biosphere', 'Source', 'Type_data', 'Design')
```

Count frequency in raw data
```{r get data column}
table(de$`Biosphere reserve`, useNA = 'always')
```

Sequence biosphere by country, remove NA, tidy values
```{r}
tmp <- bar_data %>% 
  select(Biosphere, Country) %>% 
  drop_na() %>% 
  arrange(Country, Biosphere) %>% 
  arrange(match(Country, c('Philippines', 'Vietnam', 'Cambodia', 'Indonesia', 'Thailand')))

tmp <- tmp[nrow(tmp):1,] # reverse rows if want high freq country at bottom

biosphereBycountryData <- tmp %>%
  mutate(Biosphere = replace(Biosphere, Biosphere=='Komodo MPA', 'Komodo')) %>% 
  mutate(Biosphere = replace(Biosphere, Biosphere=='Cat Tien (Dong Nai)', 'Cat Tien'))

biosphereBycountryData
```

Calculate proportion with frequency
```{r eval = TRUE, echo = TRUE}
biosphereFreq <- tabyl(biosphereBycountryData$Biosphere)
names(biosphereFreq)[1] <- 'Biosphere'

biosphereFreq <- biosphereFreq %>% 
  arrange(match(Biosphere, c('Ranong', 'Lore Lindu', 'Komodo', 'Tonle Sap', 'Red River Delta', 'Cu Lao Cham', 'Cat Tien', 'Palawan')))

biosphereFreq
```

```{r}
library(RColorBrewer)
labelonly <-  theme(
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  axis.text.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.x=element_blank(),
  axis.ticks.y=element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank()
)
GreenLong <- colorRampPalette(brewer.pal(9, 'Greens'))(16)
midGreens <- GreenLong[4:11]
BlueLong <- colorRampPalette(brewer.pal(9, 'Blues'))(15)
midBlues <- BlueLong[5:9]

midGreens
```

```{r eval = TRUE, echo = TRUE}
#thisTable <- thisTable[order(thisTable$n),]
thisTable <- biosphereFreq
Name <- thisTable$Biosphere
Value <- thisTable$percent
absolute <- thisTable$n
percent <- format(round(Value * 100, 0), nsmall = 0)
str <- paste0(Name, '  ( ', absolute, ' )')

df <-  data.frame(Name, Value) %>%
  mutate(Name = factor(Name, levels = Name),
         yPos = cumsum(lag(Value, default = 0)) + Value/2) # calculate interval position

thisPlot <- ggplot(data = df, aes(x = 'x', y = Value, fill = Name)) +
  geom_col(position = "fill", show.legend = FALSE, width = 0.4) +
  geom_text(aes(label = str),
            position = position_fill(), vjust = 2,
            size = ifelse(df$Name == 'Palawan', 4.5, 4),
            color = ifelse(df$Name == 'Palawan', 'white', 'black')) +
  labelonly +
  scale_fill_manual(values = midGreens)

ggsave(file="img/biosphere_byCountry_raw.png", plot=thisPlot)
biosphereCountryPlot <- thisPlot  
biosphereCountryPlot
```

```{r}
library(magick)
img <- image_read('img/biosphere_byCountry_raw.png')
image_info(_label_img)
tmp <- image_trim(_img)
image_write(tmp, path='img/biosphereBycountry.png', format='png')
image_info(tmp)
```
# combine country and biosphere
```{r}
country_img <- image_read('img/country_vertical.png')
image_info(country_img)
biosphere_img <- image_read('img/biosphereByCountry.png')
image_info(biosphere_img)

images <- c(country_img, biosphere_img)
cb <- image_append(image_scale(images))
image_info(cb)
image_write(cb, path='img/countryWithbiosphere.png', format='png')
```

```{r eval = TRUE, echo = TRUE}
thisTable <- biosphereFreq
Name <- thisTable$Biosphere
Value <- thisTable$percent
absolute <- thisTable$n
percent <- format(round(Value * 100, 0), nsmall = 0)
# str <- paste0(Name, '  ( ', absolute, ' )')
str <- Name

df <-  data.frame(Name, Value) %>%
  mutate(Name = factor(Name, levels = Name),
         yPos = cumsum(lag(Value, default = 0)) + Value/2) # calculate interval position

thisPlot <- ggplot(data = df, aes(x = 'x', y = Value)) +
  geom_col(position = "fill", show.legend = FALSE, width = 0.25, fill='white', color='black') +
  geom_text(aes(label = str),
            position = position_fill(), 
            vjust = 2, hjust = 0,
            size = 4, color = 'black') +
  labelonly 

# +  scale_fill_manual(values = midGreens)

ggsave(file="img/biosphereByCountry_side_raw.png", plot=thisPlot)
biosphereCountrySidePlot <- thisPlot  
biosphereCountrySidePlot
```

```{r}
library(magick)
typeOfData_label_img <- image_read('img/biosphere_vertical_raw.png')
image_info(typeOfData_label_img)
tmp <- image_trim(typeOfData_label_img)
image_write(tmp, path='img/biosphere_vertical.png', format='png')
image_info(tmp)
```

Country data, and calculate proportion
```{r eval = TRUE, echo = TRUE}
thisData <- de %>% 
  select(Country) %>% 
  drop_na()

thisTable <- tabyl(thisData$Country)
names(thisTable)[1] <- 'Country'

thisTable <- thisTable[order(thisTable$n),]
```

```{r eval = TRUE, echo = FALSE}
Name <- thisTable$Country
Value <- thisTable$percent
absolute <- thisTable$n
percentage <- format(round(Value * 100, 0), nsmall = 0)
str <- paste0(Name, '  ( ', absolute, ' )')

df <-  data.frame(Name, Value) %>%
  mutate(Name = factor(Name, levels = Name),
         yPos = cumsum(lag(Value, default = 0)) + Value/2) # calculate interval position

thisPlot <- ggplot(data = df, aes(x = 'x', y = Value, fill = Name)) +
  geom_col(position = "fill", show.legend = FALSE, width = 0.4) +
  geom_text(aes(label = str),
            position = position_fill(), vjust = 2,
            size = ifelse(df$Name == '', 4.5, 4),
            color = ifelse(df$Name == '', 'white', 'black')) +
  labelonly +
  scale_fill_manual(values = midBlues)

ggsave(file="img/country_vertical_raw.png", plot=thisPlot)
countryVerticalPlot <- thisPlot  
countryVerticalPlot
```

```{r}
img <- image_read('img/country_vertical_raw.png')
image_info(typeOfData_label_img)
tmp <- image_trim(typeOfData_label_img)
image_write(tmp, path='img/country_vertical.png', format='png')
image_info(tmp)
```

## Country with reserves named inside
```{r eval = TRUE, echo = FALSE}
Name <- thisTable$Country
Value <- thisTable$percent
absolute <- thisTable$n
percentage <- format(round(Value * 100, 0), nsmall = 0)
str <- paste0(Name, '  ( ', absolute, ' )')

df <-  data.frame(Name, Value) %>%
  mutate(Name = factor(Name, levels = Name),
         yPos = cumsum(lag(Value, default = 0)) + Value/2) # calculate interval position

thisPlot <- ggplot(data = df, aes(x = 'x', y = Value, fill = Name)) +
  geom_col(position = "fill", show.legend = FALSE, width = 0.4) +
  geom_text(aes(label = str),
            position = position_fill(), vjust = 2,
            size = ifelse(df$Name == '', 4.5, 4),
            color = ifelse(df$Name == '', 'white', 'black')) +
  labelonly +
  scale_fill_manual(values = midBlues)

ggsave(file="img/country_vertical_raw.png", plot=thisPlot)
countryVerticalPlot <- thisPlot  
countryVerticalPlot
```

```{r}
library(patchwork)
countryVerticalPlot + biosphereVerticalPlot
```

